/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of FFT.xs. Do not edit this file, edit FFT.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "FFT.xs"
#ifdef __cplusplus
extern "C" {
#endif

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "arrays.h"
#include "FFT.h"

#ifdef __cplusplus
}
#endif

#line 25 "FFT.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 77 "FFT.c"

XS(XS_Math__FFT__cdft); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__cdft)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "n, isgn, a, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	int	isgn = (int)SvIV(ST(1));
	double *        a = (double *)pack1D(ST(2),'d');
	int *        ip = (int *)pack1D(ST(3),'i');
	double *        w = (double *)pack1D(ST(4),'d');

	_cdft(n, isgn, a, ip, w);
        unpack1D((SV*)ST(2), (void *)a, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__rdft); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__rdft)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "n, isgn, a, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	int	isgn = (int)SvIV(ST(1));
	double *        a = (double *)pack1D(ST(2),'d');
	int *        ip = (int *)pack1D(ST(3),'i');
	double *        w = (double *)pack1D(ST(4),'d');

	_rdft(n, isgn, a, ip, w);
        unpack1D((SV*)ST(2), (void *)a, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__ddct); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__ddct)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "n, isgn, a, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	int	isgn = (int)SvIV(ST(1));
	double *        a = (double *)pack1D(ST(2),'d');
	int *        ip = (int *)pack1D(ST(3),'i');
	double *        w = (double *)pack1D(ST(4),'d');

	_ddct(n, isgn, a, ip, w);
        unpack1D((SV*)ST(2), (void *)a, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__ddst); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__ddst)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "n, isgn, a, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	int	isgn = (int)SvIV(ST(1));
	double *        a = (double *)pack1D(ST(2),'d');
	int *        ip = (int *)pack1D(ST(3),'i');
	double *        w = (double *)pack1D(ST(4),'d');

	_ddst(n, isgn, a, ip, w);
        unpack1D((SV*)ST(2), (void *)a, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT_pdfct); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT_pdfct)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "nt, n, a, t, ip, w");
    {
	int	nt = (int)SvIV(ST(0));
	int	n = (int)SvIV(ST(1));
	double *        a = (double *)pack1D(ST(2),'d');
	double *        t = (double *)pack1D(ST(3),'d');
	int *        ip = (int *)pack1D(ST(4),'i');
	double *        w = (double *)pack1D(ST(5),'d');
#line 69 "FFT.xs"
    coerce1D( (SV*) ST(3), nt);
    t = (double *) pack1D( (SV*) ST(3), 'd');
    _dfct(n, a, t, ip, w);
#line 200 "FFT.c"
        unpack1D((SV*)ST(2), (void *)a, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT_pdfst); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT_pdfst)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "nt, n, a, t, ip, w");
    {
	int	nt = (int)SvIV(ST(0));
	int	n = (int)SvIV(ST(1));
	double *        a = (double *)pack1D(ST(2),'d');
	double *	t;
	int *        ip = (int *)pack1D(ST(4),'i');
	double *        w = (double *)pack1D(ST(5),'d');
#line 84 "FFT.xs"
    coerce1D( (SV*) ST(3), nt);
    t = (double *) pack1D( (SV*) ST(3), 'd');
    _dfst(n, a, t, ip, w);
#line 229 "FFT.c"
        unpack1D((SV*)ST(2), (void *)a, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__correl); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__correl)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "n, corr, d1, d2, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	double *	corr;
	double *        d1 = (double *)pack1D(ST(2),'d');
	double *        d2 = (double *)pack1D(ST(3),'d');
	int *        ip = (int *)pack1D(ST(4),'i');
	double *        w = (double *)pack1D(ST(5),'d');
#line 99 "FFT.xs"
    int i;
#line 256 "FFT.c"
#line 101 "FFT.xs"
    coerce1D( (SV*) ST(1), n);
    corr = (double *) pack1D( (SV*) ST(1), 'd');
    corr[0] = d1[0]*d2[0];
    corr[1] = d1[1]*d2[1];
    for (i=2; i<n; i+=2) {
	corr[i] = d1[i]*d2[i]+ d1[i+1]*d2[i+1];
	corr[i+1] = d1[i+1]*d2[i] - d1[i]*d2[i+1];
    }
    _rdft(n, -1, corr, ip, w);
    for (i=0; i<n; i++) corr[i] *= 2.0/n;
#line 268 "FFT.c"
        unpack1D((SV*)ST(1), (void *)corr, 'd', 0);
	SvSETMAGIC(ST(1));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__convlv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__convlv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "n, convlv, d1, d2, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	double *	convlv;
	double *        d1 = (double *)pack1D(ST(2),'d');
	double *        d2 = (double *)pack1D(ST(3),'d');
	int *        ip = (int *)pack1D(ST(4),'i');
	double *        w = (double *)pack1D(ST(5),'d');
#line 123 "FFT.xs"
    int i;
#line 295 "FFT.c"
#line 125 "FFT.xs"
    coerce1D( (SV*) ST(1), n);
    convlv = (double *) pack1D( (SV*) ST(1), 'd');
    _rdft(n, 1, d2, ip, w);
    convlv[0] = d1[0]*d2[0];
    convlv[1] = d1[1]*d2[1];
    for (i=2; i<n; i+=2) {
	convlv[i] = d1[i]*d2[i]- d1[i+1]*d2[i+1];
	convlv[i+1] = d1[i+1]*d2[i] + d1[i]*d2[i+1];
    }
    _rdft(n, -1, convlv, ip, w);
    for (i=0; i<n; i++) convlv[i] *= 2.0/n;
#line 308 "FFT.c"
        unpack1D((SV*)ST(1), (void *)convlv, 'd', 0);
	SvSETMAGIC(ST(1));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__deconvlv); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__deconvlv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "n, convlv, d1, d2, ip, w");
    {
	int	n = (int)SvIV(ST(0));
	double *	convlv;
	double *        d1 = (double *)pack1D(ST(2),'d');
	double *        d2 = (double *)pack1D(ST(3),'d');
	int *        ip = (int *)pack1D(ST(4),'i');
	double *        w = (double *)pack1D(ST(5),'d');
#line 149 "FFT.xs"
    int i;
    double mag;
#line 336 "FFT.c"
	int	RETVAL;
	dXSTARG;
#line 152 "FFT.xs"
    coerce1D( (SV*) ST(1), n);
    convlv = (double *) pack1D( (SV*) ST(1), 'd');
    _rdft(n, 1, d2, ip, w);
    RETVAL=0;
    if (fabs((float)d2[0])<1.e-10  || fabs((float)d2[1])<1.e-10) {
       RETVAL=1;
    }
    else {
      convlv[0] = d1[0]/d2[0];
      convlv[1] = d1[1]/d2[1];
      for (i=2; i<n; i+=2) {
       	mag = d2[i]*d2[i] + d2[i+1]*d2[i+1];
	if (mag < 1.0e-10) {
           RETVAL =1;
           break;
        }	  
	convlv[i] = (d1[i]*d2[i]+ d1[i+1]*d2[i+1])/mag;
	convlv[i+1] = (d1[i+1]*d2[i] - d1[i]*d2[i+1])/mag;
      }
      if (RETVAL == 0) {
        _rdft(n, -1, convlv, ip, w);
        for (i=0; i<n; i++) convlv[i] *= 2.0/n;
      }
    }
#line 364 "FFT.c"
        unpack1D((SV*)ST(1), (void *)convlv, 'd', 0);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Math__FFT__spctrm); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__spctrm)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 7)
       croak_xs_usage(cv,  "n, spctrm, data, ip, w, n2, flag");
    {
	int	n = (int)SvIV(ST(0));
	double *	spctrm;
	double *        data = (double *)pack1D(ST(2),'d');
	int *        ip = (int *)pack1D(ST(3),'i');
	double *        w = (double *)pack1D(ST(4),'d');
	int	n2 = (int)SvIV(ST(5));
	int	flag = (int)SvIV(ST(6));
#line 190 "FFT.xs"
    int i;
#line 393 "FFT.c"
#line 192 "FFT.xs"
    coerce1D( (SV*) ST(1), n/2+1);
    spctrm = (double *) pack1D( (SV*) ST(1), 'd');
    if (flag == 1) _rdft(n, 1, data, ip, w);
    spctrm[0] = data[0]*data[0] / n2;
    spctrm[n/2] = data[1]*data[1] / n2;
    for (i=1; i<n/2; i++) {
      spctrm[i] = 2*(data[2*i]*data[2*i]+ data[2*i+1]*data[2*i+1])/n2;
    }
#line 403 "FFT.c"
        unpack1D((SV*)ST(1), (void *)spctrm, 'd', 0);
	SvSETMAGIC(ST(1));
    }
    XSRETURN_EMPTY;
}


XS(XS_Math__FFT__spctrm_bin); /* prototype to pass -Wmissing-prototypes */
XS(XS_Math__FFT__spctrm_bin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 8)
       croak_xs_usage(cv,  "k, m, spctrm, data, ip, w, n2, tmp");
    {
	int	k = (int)SvIV(ST(0));
	int	m = (int)SvIV(ST(1));
	double *	spctrm;
	double2D *        data = (double2D *)pack2D(ST(3),'d');
	int *        ip = (int *)pack1D(ST(4),'i');
	double *        w = (double *)pack1D(ST(5),'d');
	double	n2 = (double)SvNV(ST(6));
	double *	tmp;
#line 214 "FFT.xs"
     int i, j, n;
     double den = 0.0;
#line 433 "FFT.c"
#line 217 "FFT.xs"
    coerce1D( (SV*) ST(2), m/2+1);
    spctrm = (double *) pack1D( (SV*) ST(2), 'd');
    coerce1D( (SV*) ST(7), m);
    tmp = (double *) pack1D( (SV*) ST(7), 'd');
    for(i=0; i<k*m; i+=m) {
      for (j=0; j<m; j++) tmp[j] = data[i+j];
      _rdft(m, 1, tmp, ip, w);   
      spctrm[0] += tmp[0]*tmp[0];
      spctrm[m/2] += tmp[1]*tmp[1];
      den += n2;
      for (n=1; n<m/2; n++)
        spctrm[n] += 2*(tmp[2*n]*tmp[2*n]+ tmp[2*n+1]*tmp[2*n+1]);
    }
    den *= m;
    for (j=0; j<=m/2; j++) spctrm[j] /= den;
#line 450 "FFT.c"
        unpack1D((SV*)ST(2), (void *)spctrm, 'd', 0);
	SvSETMAGIC(ST(2));
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Math__FFT); /* prototype to pass -Wmissing-prototypes */
XS(boot_Math__FFT)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("Math::FFT::_cdft", XS_Math__FFT__cdft, file);
        newXS("Math::FFT::_rdft", XS_Math__FFT__rdft, file);
        newXS("Math::FFT::_ddct", XS_Math__FFT__ddct, file);
        newXS("Math::FFT::_ddst", XS_Math__FFT__ddst, file);
        newXS("Math::FFT::pdfct", XS_Math__FFT_pdfct, file);
        newXS("Math::FFT::pdfst", XS_Math__FFT_pdfst, file);
        newXS("Math::FFT::_correl", XS_Math__FFT__correl, file);
        newXS("Math::FFT::_convlv", XS_Math__FFT__convlv, file);
        newXS("Math::FFT::_deconvlv", XS_Math__FFT__deconvlv, file);
        newXS("Math::FFT::_spctrm", XS_Math__FFT__spctrm, file);
        newXS("Math::FFT::_spctrm_bin", XS_Math__FFT__spctrm_bin, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

